language: julia
os:
    - linux
    - osx
julia:
    - 0.6
    - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.add("LightGraphs"); Pkg.test("RobustShortestPath", coverage=true)'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'cd(Pkg.dir("RobustShortestPath")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
